apiVersion: v1
kind: Secret
metadata:
  name: dynhost-failover-config
  namespace: kube-system
type: Opaque
stringData:
  DYNHOST_USER: "fluodata.pl-cloud"
  DYNHOST_PASS: "d8c84e5a3265c5554ee787b2fe67b50"
  DYNHOST_HOSTNAME: "cloud.fluodata.pl"
  HEALTH_URL_TEMPLATE: "https://__IP__:6443/healthz"
  CHECK_INTERVAL: "30"
  TEST_ROTATE_INTERVAL: "180"
