apiVersion: v1
kind: Secret
metadata:
    name: test-sops-secret
    namespace: default
type: Opaque
stringData:
    test-key: ENC[AES256_GCM,data:usyUpcrXR8AVla/bCSAM52jexiaz,iv:hm2iwx6l1IKJKplQuCWVMz1uEzo6Vrs9eOA+vmvGzgw=,tag:6ueyi8hRRBblO+FAbAFDfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10xapwe62eqng7dhf4evrj3kswd7xqfna5t3lku7hz2gghy2j0etqsspzr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNFJCcVJMTDFuRjdGOFp0
            SEZWZXZ4Zyt2Zy9kQW5YTm5BMVIvdWo1Umx3CnAwNUM0Mk9zaUdCUndmSENpeXpu
            VkFBYjlOS2tOVi9WeGd4aUpsSk1KbE0KLS0tIG1zOEFPZGZEeHA1Tlp2K3dtekJW
            R1NWaktLNVk0OTlmSmpjOUg5ZGZ1V28K6/saxvUDj6r82yw1BhUcrSOu78G5vSfi
            0ZAqcXUxOJdK35e8UyEw+X+cGFUiCfFeFr5/V4Tp2dipZRcAOKiIrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T09:28:49Z"
    mac: ENC[AES256_GCM,data:ShdT5fcyKkyo6FG4sen3xgUrVV2kpJW02RT019bbUBbhlxVM3q3P1tFZyFAA7+SjJM18+fu/8jkfXb/3BcuRNhJARdRQx851CfZkne5njkWWjzMr76VR5qCRavu75sAr7h/eGDANoUZqX2KZ6SgwTEyr+fapmP16PGMXOnOd9zY=,iv:LCdgCWZZ6wxcYPfGKaYwK/6pR1FtATkCTjcSCzqZ4Z8=,tag:KGLMLrjFlzg26eYc27zAFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
