apiVersion: v1
kind: Namespace
metadata:
  name: cnpg
  labels:
    # local-path provisioner helper pods use hostPath; allow privileged pods
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
