# Mosquitto password file.
# User: device / Password: r82nsjoqVHUjy9ZziNtW
# To add more users, run:
#   docker run --rm eclipse-mosquitto:2.0 sh -c \
#     'mosquitto_passwd -b -c /tmp/pw <user> <pass> && cat /tmp/pw'
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-passwd
  namespace: mqtt
type: Opaque
stringData:
  passwd: |
    device:$7$101$ehv58/mHdjuoKceg$yZFuUPuUh0cR2RPZn3L9AHgAHXyT0N6JZo2DTGchbWo7svO3gE7zcp53Xobd9D29R5RTuliGEqAQr9lizVA8rw==
