apiVersion: v1
kind: Namespace
metadata:
  name: scylla-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scylla-operator
  namespace: scylla-operator
  labels:
    app.kubernetes.io/name: scylla-operator
    app.kubernetes.io/instance: scylla-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-server
  namespace: scylla-operator
  labels:
    app.kubernetes.io/name: webhook-server
    app.kubernetes.io/instance: webhook-server
